### ISSUE TITLE
Can't download as file from binary response in React component

### ISSUE THREAD

**Issue by stormfar** [exportsdk/exportsdk-js#5]
Using an API call that returns a `Response<Uint8Array>`, I'm trying to convert the binary data into a PDF that can be downloaded in a React component.

Using Next.js 13.2's API route handlers, the PDF is generated like this:
```typescript
export async function POST(request: NextRequest) {
  const binaryResponse = await client.renderPdf(templateId, data);

  // Just to test, this works. The PDF can be written successfully from the backend
  // const writeFileAsync = promisify(fs.writeFile);
  // await writeFileAsync("file.pdf", Buffer.from(binaryResponse.data))

  return NextResponse.json(binaryResponse);
}
```
Then in the React component, the response is handled like this
```typescript
const response = await fetch('/api/pdf', { method: 'post' });
if (!response.ok) {
  throw new Error('Failed to generate PDF');
}

const buffer = await response.arrayBuffer();
const uint8Array = new Uint8Array(buffer);
const blob = new Blob([uint8Array], { type: 'application/pdf' });

// Also tried this 
// const blob = await response.blob();
// const url = URL.createObjectURL(blob);

saveAs(blob, 'file.pdf');
```
The resulting file that is downloaded is corrupt. If I pull it into a plain text editor, the PDF just contains the raw binary response instead of the rendered content.
```
{"data":{"0":37,"1":80,"2":68,"3":70,"4":45,"5":49,"6":46,"7":51,"8":10,"9":37,..."status":200}
```
What am I doing wrong? Can you provide an example of how to convert the binary response to a file in a React component?

Note: If I generate the PDF directly from the component, it works
```typescript
const binaryResponse = await client.renderPdf(templateId, values);
const blob = new Blob([binaryResponse.data], { type: 'application/pdf' });
saveAs(blob, 'file.pdf');
```
which makes me think the issue is in the response from the API call, or how it's handled.

**Comment by allenksun** [comment]
I am not super familiar with how Next handles responses but one possible reason for this issue is that you might be using the wrong content type in your API response. When you use NextResponse.json() to send a binary response, it will try to convert it to a JSON object. However, binary data is not valid JSON, which can cause the data to become corrupted. Could you try using NextResponse.send() along with setting the 'Content-Type' header to 'application/octet-stream'. Your React front-end code could probably remain the same, but try this out and let me know if that worked or didn't work for you.

**Comment by stormfar** [comment]
That did the trick! Modified the code to look like this:
```
export async function POST(request: NextRequest) {
  const binaryPDF = await client.renderPdf(templateId, data);

  return new NextResponse(
    binaryPDF.data,
    { headers: { 'content-type': 'application/octet-stream' } }
  )
}
```
and now it generates the PDF successfully on the frontend.

Thanks for your help!
